# Generated by Django 3.2.4 on 2021-07-14 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название канала:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Лого канала')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order_num', models.IntegerField(verbose_name='Приоритет по фильтрации')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Текст заказа')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона клиента')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('total_price', models.FloatField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Открыт'), ('Paid', 'Оплачен'), ('Closed', 'Закрыт')], default='Open', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.channel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.channel')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.IntegerField(verbose_name='Минимальное количество дней')),
                ('percent', models.IntegerField(verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('order_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.orderdetail')),
            ],
        ),
    ]
