# Generated by Django 3.2.4 on 2021-07-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
