# Generated by Django 3.2.4 on 2021-07-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210714_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='order_detail_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
    ]
